steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/parseopy/parseo-app:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/parseopy/parseo-app:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'seo-analysis-api', 
    '--image', 'gcr.io/parseopy/parseo-app:$COMMIT_SHA',
    '--platform', 'managed',
    '--region', 'us-central1',
    '--allow-unauthenticated'
  ]
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
logsBucket: gs://parseo-app
images:
  - 'gcr.io/parseopy/parseo-app:$COMMIT_SHA'
timeout: '1200s'
service_account: parseo2-0@parseopy.iam.gserviceaccount.com
