<antArtifact identifier="cloudbuild" type="application/vnd.ant.code" title="Cloud Build Configuration">
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/seo-analysis-api', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/seo-analysis-api']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'seo-analysis-api', 
    '--image', 'gcr.io/$PROJECT_ID/seo-analysis-api',
    '--platform', 'managed',
    '--region', 'us-central1',
    '--allow-unauthenticated'
  ]

