steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/parseo', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/parseo']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'parseo', '--image', 'gcr.io/$PROJECT_ID/parseo', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
