# This YAML file defines the build configuration for Cloud Build

# Define a build step
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/seo-analyzer:latest', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'seo-analyzer', 
          '--image', 'gcr.io/ParseoPy/seo-analyzer:latest',
          '--platform', 'managed',
          '--region', 'us-central1']  # Change region as needed

# Define substitutions (replace PROJECT_ID with your actual project ID)
substitutions:
  _PROJECT_ID: ParseoPy

# Optional: Specify triggers for automatic builds (e.g., on push to Git)
# triggers:
# - cloud-source-repository: your-repo-name  # Replace with your repo name
